framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr
    http_method_override: true
    session:
        handler_id: ~

    php_errors:
        log: true

    cache:
        app: cache.adapter.filesystem
